version: 2.1
orbs:
  rn: react-native-community/react-native@4.4.2

jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn lint
          name: Run ESLint
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - run:
          name: Create .env file
          command: echo $ENV_DEV > .env
      - persist_to_workspace:
          paths: .
          root: .

workflows:
  build:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/android_build:
          build_type: release
          requires:
            - analyse_js
