version: 2.1
orbs:
  rn: react-native-community/react-native@4.4.2

jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn lint
          name: Run ESLint
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - run:
          name: Create .env file
          command: |
            if [[ "$CIRCLE_TAG" =~ ^v.*-staging$ ]]; then
              echo $ENV_STAGING > .env
            else
              echo $ENV_DEV > .env
            fi
      - persist_to_workspace:
          paths: .
          root: .

workflows:
  build:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /^v.*/
      - analyse_js:
          requires:
            - checkout_code
          filters:
            tags:
              only: /^v.*/
      - rn/android_build:
          build_type: release
          requires:
            - analyse_js
          filters:
            tags:
              only: /^v.*/
