name: Build Android

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install: 
    name: Install dependencies
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint