name: Build Android

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    # branches:
    #   - master
  pull_request:
    branches:
      - master

  # Also trigger on release created events
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      # set up environment variables required for the build
      - name: Set environment variables
        run: |
          echo "OWM_APP_ID=${{ secrets.OWM_APP_ID }}" >> .env
          echo "WEATHERBIT_API_KEY=${{ secrets.WEATHERBIT_API_KEY }}" >> .env

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Build Android APK
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release --no-daemon

      # cache the APKs to be used in the detox e2e test
      - name: Cache APKs
        uses: actions/cache@v2
        with:
          path: android/app/build/outputs/apk
          key: output-apks-${{ hashFiles('package.json') }}

  test:
    name: Run Tests
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Cache APKs
        id: apk_cache
        uses: actions/cache@v2
        with:
          path: android/app/build/outputs/apk
          key: output-apks-${{ hashFiles('package.json') }}

      - name: List hardware profiles
        run: avdmanager list

      - name: Run e2e tests
        if: steps.apk_cache.outputs.cache-hit == 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          avd-name: 'Pixel_2_API_29'
          profile: 'Pixel 3'
          script: yarn test-e2e
